-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 14:47:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `idAsignatura` INT NOT NULL,
  `Notas_idNotas` INT NOT NULL,
  `Notas_Notas_idNotas` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas` (
  `idNotas` INT NOT NULL,
  `CodigoAsig` VARCHAR(45) NULL,
  `CodigoEstudiante` VARCHAR(45) NULL,
  `Nota1` INT NULL,
  `Nota2` VARCHAR(45) NULL,
  `Nota3` VARCHAR(45) NULL,
  `Notas_idNotas` INT NOT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_idAsignatura1` INT NOT NULL,
  `Estudiante_idEstudiante1` INT NOT NULL,
  PRIMARY KEY (`idNotas`, `Notas_idNotas`, `Asignatura_idAsignatura`),
  INDEX `fk_Notas_Asignatura1_idx` (`Asignatura_idAsignatura1` ASC) VISIBLE,
  INDEX `fk_Notas_Estudiante1_idx` (`Estudiante_idEstudiante1` ASC) VISIBLE,
  CONSTRAINT `fk_Notas_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura1`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante1`)
    REFERENCES `mydb`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
